# Generated by Django 4.2.5 on 2023-09-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_user_register'),
        ('registerUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
    ]
