# Generated by Django 4.1.5 on 2023-10-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_user_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
